version: '3'
services:
  web:
    image: cf-webhook
    build: .
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - BACKING_STORAGE=memory
    init: true
    ports:
      - "8787:8787"
